name: CD - Deploy to Production

on:
  workflow_run:
    workflows: ["CI - Build and Test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace
      
      - name: Deploy to production server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/filmflex
            git pull
            npm ci --production
            npm run build
            
            # Run database migrations
            DATABASE_URL="${{ secrets.DATABASE_URL }}" npm run db:push
            
            # Restart the application
            pm2 reload filmflex
            
            # Log successful deployment
            echo "Deployment completed at $(date)" >> /var/log/filmflex-deploy.log
          EOF
      
      - name: Verify deployment
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_IP "curl -sSf http://localhost:5000/api/health || exit 1"
          echo "✅ Deployment verified successfully!"