name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: filmflex
          POSTGRES_PASSWORD: filmflex
          POSTGRES_DB: filmflex
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run type check
      run: npm run check
    
    - name: Build application
      run: npm run build
      
    - name: Run database migrations
      run: npm run db:push
      env:
        DATABASE_URL: postgresql://filmflex:filmflex@localhost:5432/filmflex
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-folder
        path: |
          dist
          client/dist