name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 38.54.115.156
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/filmflex
            git pull
            npm ci
            npm run build
            pm2 reload filmflex || pm2 start --name filmflex dist/index.js
            pm2 save